services:
  - type: web
    name: markethero-api
    env: node
    autoDeploy: true
    plan: free
    rootDir: .
    buildCommand: ""
    startCommand: "node server/index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 7d
      - key: FRONTEND_URLS
        sync: false
      - key: OPENAI_API_KEY
        sync: false
